<a href="https://colab.research.google.com/github/DanielSan33-4/ITA.Sprint07/blob/main/Sprint07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tasca S7.01. Creació de funcions, estructures de dades i bucles

## Nivell 1

### Exercici 1: Selecció de personal

Per això, t'han encarregat desenvolupar una eina senzilla en Python que actuï com a formulari d'inscripció i sistema de classificació inicial. Aquest formulari ha de permetre introduir, per a cada candidat/a:

- Nom i Cognoms
- Telèfon de contacte
- Anys d'experiència dins de l'empresa
- Coneixement de Català (0–3 punts)
  * 0 = sense coneixement
  * 1 = fins a nivell B1
  * 2 = nivell B2
  * 3 = C1 o superior
- Domini d'Excel (0–3 punts)
  * 0 = nivell bàsic
  * 1 = ús de funcions
  * 2 = taules dinàmiques
  * 3 = Visual Basic i Macros
- Títol acadèmic (0–3 punts)
  * 0 = ESO
  * 1 = FP
  * 2 = Universitat
  * 3 = Màster o superior

Assegurant-se que tota la informació introduïda és correcta i entra dins els valors permesos. A partir d'aquestes dades, el programa haurà de calcular una puntuació total aplicant el pes de l'experiència (anys * 1.5) i sumant-hi els punts de català, excel i titulació, i a continuació classificar automàticament cada persona segons els llindars establerts per l'empresa:

- Prioritat Alta → puntuació ≥ 12
- Candidat adequat → 8 ≤ puntuació < 12
- No prioritari → puntuació < 8

Cada vegada que algú complet a el formulari, s'ha de mostrar la seva puntuació individual. Quan ja s'hagin inscrit exactament deu persones, l'eina ha de deixar d'acceptar nous registres i generar un informe final en pantalla, ordenat primer segons la prioritat i, en cas d'empat, per la puntuació obtinguda. Aquest informe ha d'incloure el nom, el telèfon i la puntuació de cada candidat per tal que el departament de RRHH els pugui contactar ràpidament.

**Important**

Per resoldre aquest exercici, hauràs de:

- Desenvolupar un sistema modular amb les funcions següents:
  * obtenir_dades
  * validar_dades
  * calcular_puntuacio
  * classificar_candidat
  * mostrar_individual
  * mostrar_informe
  * main_seleccio # orquestra totes les funcions
- Escriure primer l'algoritme pas a pas, indicant clarament quines operacions farà cada funció.
- Escriure el codi de cada funció.

Función para obtener los datos mediante inputs.

In [ ]:
def obtenir_dades():
  nom = input("Introdueixi el seu nom i cognoms: ")
  telefon = input("Introdueixi el seu número de contacte, si us plau, usi nou dígits: ")
  anys_exp = input("Introdueixi els anys d'experiència a l'empresa: ")
  con_cat = input("Introdueixi el seu domini del català. Usi: 0 sense coneixement, 1 fins a B1, 2 B2 i 3 per C1 o superior: ")
  dom_exel = input("Introdueixi el seu domini de l'Excel. Usi: 0 per nivell bàsic, 1 ús de funcions, 2 taules dinàmiques i 3 Visual Basic i Macros: ")
  tit_academic = input("Introdueixi la seva titulació acadèmica més alta. Usi: 0 ESO, 1 FP, 2 Universitat i 3 Màster o superior: ")
  return nom, telefon, anys_exp, con_cat, dom_exel, tit_academic

La siguiente función limpia los datos (tipo y comas/puntos) y revisa que las condiciones necesarias para el uso de estos datos sean las correctas.
Se usan las siguientes condiciones:

- `while True` para aceptar tantos fallos del usuario como sea necesario antes de dar por bueno el input.
- `try` para gestionar el posible ValueError en caso de no usar un número entero.
- La condición if...break, apra permanecer en el bucle mientras no se introduzca un dígito de una longitud igual a 9.
- Con anys_exp queremos limpiar la entrada para modificar comas por puntos y permanecer en el bucle hasta obtener un dígito viable.
- Para los tres últimos inputs se acepta únicamente números enteros y dentro del conjunto {0,1,2,3}.

In [ ]:
def validar_dades(nom, telefon, anys_exp, con_cat, dom_exel, tit_academic):
  if not (telefon.isdigit() and len(telefon) == 9):
    return False, "Error: El telèfon ha de contenir exactament 9 dígits numèrics."
  try:
        anys_net = anys_exp.replace(",", ".")
        anys_exp_final = float(anys_net)
  except ValueError:
        return False, "Error: Els anys d'experiència han de ser un número vàlid."
  try:
      con_cat_final = int(con_cat)
      if con_cat_final not in {0, 1, 2, 3}:
          return False, "Error: El domini del català ha de ser 0, 1, 2 o 3."
  except ValueError:
      return False, "Error: El domini del català ha de ser un número enter."
  try:
      dom_exel_final = int(dom_exel)
      if dom_exel_final not in {0, 1, 2, 3}:
          return False, "Error: El domini de l'Excel ha de ser 0, 1, 2 o 3."
  except ValueError:
      return False, "Error: El domini de l'Excel ha de ser un número enter."
  try:
      tit_academic_final = int(tit_academic)
      if tit_academic_final not in {0, 1, 2, 3}:
          return False, "Error: La titulació acadèmica ha de ser 0, 1, 2 o 3."
  except ValueError:
      return False, "Error: La titulació acadèmica ha de ser un número enter."
  return True, (nom, telefon, anys_exp_final, con_cat_final, dom_exel_final, tit_academic_final)

Función para calcular la puntuación obtenida.

In [ ]:
def calcular_puntuacio(nom, telefon, anys_exp_final, con_cat_final, dom_exel_final, tit_academic_final):
  anys_exp_calcul = anys_exp_final * 1.5
  puntuacio_final = anys_exp_calcul + con_cat_final + dom_exel_final + tit_academic_final
  return nom, telefon, puntuacio_final

Función para categorizar cada perfil candidato. La función se parará con el décimo candidato.

In [ ]:
def classificar_candidat(puntuacio_final):
  if puntuacio_final < 8:
    classificacio = "Prioritat baixa"
  elif puntuacio_final < 12:
    classificacio = "Perfil adequat"
  else:
    classificacio = "Prioritat alta"
  return classificacio

Función para mostrar un informe del perfil individual del candidato.

In [ ]:
def mostrar_individual(nom, telefon, puntuacio_final, classificacio):
  print(f' El candidat {nom} amb telèfon de contacte {telefon} ha obtingut una puntuació de: {puntuacio_final}, quedant classificat com {classificacio}')

Función para mostrar un informe de todos los candidatos presentados, ordenados por puntuación.

Para ello se crea un diccionario con la classificación por puntuación deseada como clave y un conjunto de la información de cada candidato como valor.

Se clasifican los candidatos según la prioridad extraída de la lista de candidatos creada en la función `main`con toda la información resultante de las funciones anteriores.

Por último se imprime un resumen con el nombre, teléfono y puntuación de cada candidato, clasificado según el valor `classificació`.

In [ ]:
def mostrar_informe(llista_candidats):
  classificacio_perfils = {
      "Prioritat alta": [],
      "Perfil adequat": [],
      "Prioritat baixa": []
  }
  for candidat in llista_candidats:
    classificacio = candidat["classificació"]
    if classificacio in classificacio_perfils:
      classificacio_perfils[classificacio].append(candidat)
  for categoria, perfils in classificacio_perfils.items():
    perfils_ordenats = sorted(perfils, key=lambda candidat:candidat["puntuació"], reverse = True)
    print(categoria)
    for perfil in perfils_ordenats:
      print(f' - {perfil["nom"]}, {perfil["telèfon"]}, puntuació: {perfil["puntuació"]}')

Por último se monta una función que enseñe y recorra todos los candidatos.

Esta función se basa en un `while`que se rompe a la que se introduzca la información **válida** del décimo candidato.

El bucle recorre las diferentes funciones hasta crear un diccionario con la información de los candidatos que se van introduciendo.

Una vez se llega al décimo se rompe y se llama la última función, que usando esta lista crea la clasificación final y ordenada.

In [ ]:
def main_seleccio():
  llista_candidats = []
  candidats = 0
  while candidats < 10:
    print(f'Candidat {candidats + 1} de 10')
    while True:
      nom, telefon, anys_exp, con_cat, dom_exel, tit_academic = obtenir_dades()
      candidat_valid, info_candidat = validar_dades(nom, telefon, anys_exp, con_cat, dom_exel, tit_academic)
      if candidat_valid:
        nom, telefon, anys_exp_final, con_cat_final, dom_exel_final, tit_academic_final = info_candidat
        break
      else:
        print("Informació no vàlida, cal tornar a indicar-la.")
    nom, telefon, puntuacio_final = calcular_puntuacio(nom, telefon, anys_exp_final, con_cat_final, dom_exel_final, tit_academic_final)
    classificacio = classificar_candidat(puntuacio_final)
    candidat_actual = {
        "nom": nom,
        "telèfon": telefon,
        "puntuació": puntuacio_final,
        "classificació": classificacio
    }
    llista_candidats.append(candidat_actual)
    candidats += 1
    mostrar_individual(nom, telefon, puntuacio_final, classificacio)
  mostrar_informe(llista_candidats)

In [ ]:
main_seleccio()

Candidat 1 de 10
Introdueixi el seu nom i cognoms: Laura Serra
Introdueixi el seu número de contacte, si us plau, usi nou dígits: 608112233
Introdueixi els anys d'experiència a l'empresa: 6
Introdueixi el seu domini del català. Usi: 0 sense coneixement, 1 fins a B1, 2 B2 i 3 per C1 o superior: 3
Introdueixi el seu domini de l'Excel. Usi: 0 per nivell bàsic, 1 ús de funcions, 2 taules dinàmiques i 3 Visual Basic i Macros: 3
Introdueixi la seva titulació acadèmica més alta. Usi: 0 ESO, 1 FP, 2 Universitat i 3 Màster o superior: 3
Candidat 2 de 10
Introdueixi el seu nom i cognoms: Clara Gómez
Introdueixi el seu número de contacte, si us plau, usi nou dígits: 655221199
Introdueixi els anys d'experiència a l'empresa: 3
Introdueixi el seu domini del català. Usi: 0 sense coneixement, 1 fins a B1, 2 B2 i 3 per C1 o superior: 3
Introdueixi el seu domini de l'Excel. Usi: 0 per nivell bàsic, 1 ús de funcions, 2 taules dinàmiques i 3 Visual Basic i Macros: 3
Introdueixi la seva titulació acadèmica més alta. Usi: 0 ESO, 1 FP, 2 Universitat i 3 Màster o superior: 2
Candidat 3 de 10
Introdueixi el seu nom i cognoms: Sergio López
Introdueixi el seu número de contacte, si us plau, usi nou dígits: 644112211
Introdueixi els anys d'experiència a l'empresa: 3
Introdueixi el seu domini del català. Usi: 0 sense coneixement, 1 fins a B1, 2 B2 i 3 per C1 o superior: 2
Introdueixi el seu domini de l'Excel. Usi: 0 per nivell bàsic, 1 ús de funcions, 2 taules dinàmiques i 3 Visual Basic i Macros: 2
Introdueixi la seva titulació acadèmica més alta. Usi: 0 ESO, 1 FP, 2 Universitat i 3 Màster o superior: 2
Candidat 4 de 10
Introdueixi el seu nom i cognoms: Candidat Error
Introdueixi el seu número de contacte, si us plau, usi nou dígits: 611000000
Introdueixi els anys d'experiència a l'empresa: 5
Introdueixi el seu domini del català. Usi: 0 sense coneixement, 1 fins a B1, 2 B2 i 3 per C1 o superior: 7
Introdueixi el seu domini de l'Excel. Usi: 0 per nivell bàsic, 1 ús de funcions, 2 taules dinàmiques i 3 Visual Basic i Macros: 3
Introdueixi la seva titulació acadèmica més alta. Usi: 0 ESO, 1 FP, 2 Universitat i 3 Màster o superior: 2
Informació no vàlida, cal tornar a indicar-la.
Introdueixi el seu nom i cognoms: Marta Ruíz
Introdueixi el seu número de contacte, si us plau, usi nou dígits: 699887766
Introdueixi els anys d'experiència a l'empresa: 2
Introdueixi el seu domini del català. Usi: 0 sense coneixement, 1 fins a B1, 2 B2 i 3 per C1 o superior: 3
Introdueixi el seu domini de l'Excel. Usi: 0 per nivell bàsic, 1 ús de funcions, 2 taules dinàmiques i 3 Visual Basic i Macros: 2
Introdueixi la seva titulació acadèmica més alta. Usi: 0 ESO, 1 FP, 2 Universitat i 3 Màster o superior: 1
Candidat 5 de 10
Introdueixi el seu nom i cognoms: Marc Vidal
Introdueixi el seu número de contacte, si us plau, usi nou dígits: 612443322
Introdueixi els anys d'experiència a l'empresa: 6
Introdueixi el seu domini del català. Usi: 0 sense coneixement, 1 fins a B1, 2 B2 i 3 per C1 o superior: 3
Introdueixi el seu domini de l'Excel. Usi: 0 per nivell bàsic, 1 ús de funcions, 2 taules dinàmiques i 3 Visual Basic i Macros: 3
Introdueixi la seva titulació acadèmica més alta. Usi: 0 ESO, 1 FP, 2 Universitat i 3 Màster o superior: 3
Candidat 6 de 10
Introdueixi el seu nom i cognoms: Júlia Romero
Introdueixi el seu número de contacte, si us plau, usi nou dígits: 677998877
Introdueixi els anys d'experiència a l'empresa: 5
Introdueixi el seu domini del català. Usi: 0 sense coneixement, 1 fins a B1, 2 B2 i 3 per C1 o superior: 3
Introdueixi el seu domini de l'Excel. Usi: 0 per nivell bàsic, 1 ús de funcions, 2 taules dinàmiques i 3 Visual Basic i Macros: 3
Introdueixi la seva titulació acadèmica més alta. Usi: 0 ESO, 1 FP, 2 Universitat i 3 Màster o superior: 2
Candidat 7 de 10
Introdueixi el seu nom i cognoms: Pol Navarro
Introdueixi el seu número de contacte, si us plau, usi nou dígits: 699554433
Introdueixi els anys d'experiència a l'empresa: 4
Introdueixi el seu domini del català. Usi: 0 sense coneixement, 1 fins a B1, 2 B2 i 3 per C1 o superior: 3
Introdueixi el seu domini de l'Excel. Usi: 0 per nivell bàsic, 1 ús de funcions, 2 taules dinàmiques i 3 Visual Basic i Macros: 2
Introdueixi la seva titulació acadèmica més alta. Usi: 0 ESO, 1 FP, 2 Universitat i 3 Màster o superior: 2
Candidat 8 de 10
Introdueixi el seu nom i cognoms: David Ferrer
Introdueixi el seu número de contacte, si us plau, usi nou dígits: 677665544
Introdueixi els anys d'experiència a l'empresa: 2
Introdueixi el seu domini del català. Usi: 0 sense coneixement, 1 fins a B1, 2 B2 i 3 per C1 o superior: 1
Introdueixi el seu domini de l'Excel. Usi: 0 per nivell bàsic, 1 ús de funcions, 2 taules dinàmiques i 3 Visual Basic i Macros: 1
Introdueixi la seva titulació acadèmica més alta. Usi: 0 ESO, 1 FP, 2 Universitat i 3 Màster o superior: 1
Candidat 9 de 10
Introdueixi el seu nom i cognoms: Anna Paredes
Introdueixi el seu número de contacte, si us plau, usi nou dígits: 633221144
Introdueixi els anys d'experiència a l'empresa: 1
Introdueixi el seu domini del català. Usi: 0 sense coneixement, 1 fins a B1, 2 B2 i 3 per C1 o superior: 2
Introdueixi el seu domini de l'Excel. Usi: 0 per nivell bàsic, 1 ús de funcions, 2 taules dinàmiques i 3 Visual Basic i Macros: 1
Introdueixi la seva titulació acadèmica més alta. Usi: 0 ESO, 1 FP, 2 Universitat i 3 Màster o superior: 0
Candidat 10 de 10
Introdueixi el seu nom i cognoms: Anibal Paredes
Introdueixi el seu número de contacte, si us plau, usi nou dígits: 644272727
Introdueixi els anys d'experiència a l'empresa: 1
Introdueixi el seu domini del català. Usi: 0 sense coneixement, 1 fins a B1, 2 B2 i 3 per C1 o superior: 2
Introdueixi el seu domini de l'Excel. Usi: 0 per nivell bàsic, 1 ús de funcions, 2 taules dinàmiques i 3 Visual Basic i Macros: 1
Introdueixi la seva titulació acadèmica més alta. Usi: 0 ESO, 1 FP, 2 Universitat i 3 Màster o superior: 0
Prioritat alta
 - Laura Serra, 608112233, puntuació: 18.0
 - Marc Vidal, 612443322, puntuació: 18.0
 - Júlia Romero, 677998877, puntuació: 15.5
 - Pol Navarro, 699554433, puntuació: 13.0
 - Clara Gómez, 655221199, puntuació: 12.5
Perfil adequat
 - Sergio López, 644112211, puntuació: 10.5
 - Marta Ruíz, 699887766, puntuació: 9.0
Prioritat baixa
 - David Ferrer, 677665544, puntuació: 6.0
 - Anna Paredes, 633221144, puntuació: 4.5
 - Anibal Paredes, 644272727, puntuació: 4.5

Cuando se llega al candidato error, la función vuelve a pedir la información para ese número de candidato, sin pasar al siguiente. Una vez se introducen los diez, no pide un undécimo, sino que enseña como estos quedan clasificados y las puntuaciones obtenidas.

### Exercici 2: Segmentació per risc de cistella de compra

Disposes d'un conjunt de dades amb informació bàsica de 10 clients:

- id_client
- nom
- edat
- grup_edat
- codi_comportament
                
```
clients = [
    {"id_client": 1, "nom": "Laura Serra", "edat": 23, "grup_edat": "18-25", "codi_comportament": 4},
    {"id_client": 2, "nom": "Marc Vidal", "edat": 35, "grup_edat": "26-40", "codi_comportament": 3},
    {"id_client": 3, "nom": "Ana López", "edat": 29, "grup_edat": "26-40", "codi_comportament": 2},
    {"id_client": 4, "nom": "Joan Riera", "edat": 19, "grup_edat": "18-25", "codi_comportament": 2},
    {"id_client": 5, "nom": "Mónica Pérez", "edat": 47, "grup_edat": "41-60", "codi_comportament": 4},
    {"id_client": 6, "nom": "Luis García", "edat": 52, "grup_edat": "41-60", "codi_comportament": 1},
    {"id_client": 7, "nom": "Pilar Sánchez", "edat": 61, "grup_edat": "60+", "codi_comportament": 3},
    {"id_client": 8, "nom": "Eva Martín", "edat": 38, "grup_edat": "26-40", "codi_comportament": 0},
    {"id_client": 9, "nom": "Diego Romero", "edat": 24, "grup_edat": "18-25", "codi_comportament": 1},
    {"id_client": 10, "nom": "Núria Costa", "edat": 33, "grup_edat": "26-40", "codi_comportament": 4}
]
```
         
El departament de CRM ha definit manualment:

-  Codis de comportament

0 → Navega però no afegeix productes

1 → Afegeix productes però no arriba al checkout

2 → Arriba al checkout però no paga

3 → Cistella de compra abandonat fa menys de 24 h

4 → Cistella de compra abandonat fa més de 24 h

- Factors segons codi de comportament

Codi 0 → 0.10

Codi 1 → 0.25

Codi 2 → 0.50

Codi 3 → 0.75

Codi 4 → 0.90

- Factors segons grup d'edat

18–25 → 1.20

26–40 → 1.00

41–60 → 0.85

60+ → 0.70

-  Fórmula del risc final

risc_final = factor codi * factor edat

Un cop processats els clients, has de ser capaç de respondre:

- 1. Quins clients s'han de contactar primer en una campanya de retargeting?
- 2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents? (Per exemple: un client jove que abandona la cistella de compra fa 24 h té el mateix risc que un de més edat?)
- 3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?
- 4. Quin client seria el més rendible de recuperar?
Interpretant el risc final i el segment.


Requisits tècnics del teu programa

Hauràs de construir un sistema modular utilitzant diverses funcions i, sobretot, sense utilitzar if/elif/else per fer la segmentació.

**Important**

Per resoldre aquest exercici, hauràs de:

- Desenvolupar un sistema modular amb les funcions següents:
- S'ha d'implementar amb un diccionari de diccionaris, sense condicions.
  * processar_clients # s'ha d'alimentar de les funcions següents:
    * obtenir_segment_i_factor
    * obtenir_factor_edat
    * calcular_risc
  * mostrar_dataframe o mostrar_diccionari
  * mostrar_respostes
  * main_marketing # orquestra totes les funcions
- Escriure primer l'algoritme pas a pas, indicant clarament quines operacions farà cada funció.
- Escriure el codi de cada funció.


**Resultat esperat**

Un DataFrame o diccionari final amb:

- id_cliente
- nombre
- edad
- grupo_edad
- codigo_comportamiento
- segment
- missatge
- factor_codi
- factor_edat
- risc_final

I capacitat per respondre totes les preguntes de màrqueting demanades en una funció.

In [ ]:
# Tabla con los datos:
clients = [
    {"id_client": 1, "nom": "Laura Serra", "edat": 23, "grup_edat": "18-25", "codi_comportament": 4},
    {"id_client": 2, "nom": "Marc Vidal", "edat": 35, "grup_edat": "26-40", "codi_comportament": 3},
    {"id_client": 3, "nom": "Ana López", "edat": 29, "grup_edat": "26-40", "codi_comportament": 2},
    {"id_client": 4, "nom": "Joan Riera", "edat": 19, "grup_edat": "18-25", "codi_comportament": 2},
    {"id_client": 5, "nom": "Mónica Pérez", "edat": 47, "grup_edat": "41-60", "codi_comportament": 4},
    {"id_client": 6, "nom": "Luis García", "edat": 52, "grup_edat": "41-60", "codi_comportament": 1},
    {"id_client": 7, "nom": "Pilar Sánchez", "edat": 61, "grup_edat": "60+", "codi_comportament": 3},
    {"id_client": 8, "nom": "Eva Martín", "edat": 38, "grup_edat": "26-40", "codi_comportament": 0},
    {"id_client": 9, "nom": "Diego Romero", "edat": 24, "grup_edat": "18-25", "codi_comportament": 1},
    {"id_client": 10, "nom": "Núria Costa", "edat": 33, "grup_edat": "26-40", "codi_comportament": 4}
]

# Para resolver este ejercicio elijo usar DF en lugar de diccionaris, por lo tanto, importo la librería pandas.
import pandas as pd

clients_df = pd.DataFrame(clients)

Es importante tener en cuenta que la tabla `clients` se debe convertir a df para poderlo tratar con los métodos para df de pandas.

Con el método map() que modificará todas las filas de la columna seleccionada según la coincidencia clave:valor del nuevo diccionario indicado.

De esta manera, se crea una nueva columna `factors_comportament`con el factor de comportamiento según el valor indicado en la columna `codi_comportament`.

In [ ]:
def obtenir_segment_i_factor(df_p):
  factors_comportament_dicc = {
      0: 0.10,
      1: 0.25,
      2: 0.50,
      3: 0.75,
      4: 0.90
  }
  df_p["factor_comportament"] = df_p["codi_comportament"].map(factors_comportament_dicc)
  return df_p

De la misma manera que se usa map() para la función anterior, se usa para esta.

In [ ]:
def obtenir_factor_edat(df_p):
  factor_edat_dicc = {
      "18-25": 1.20,
      "26-40": 1.00,
      "41-60": 0.85,
      "60+": 0.70
  }
  df_p["factor_edat"] = df_p["grup_edat"].map(factor_edat_dicc)
  return df_p

Función para calcular el riesgo de cada cliente según sus factores de edad y comportamiento.

In [ ]:
def calcular_risc(df_p):
  df_p["risc"] = df_p["factor_edat"] * df_p["factor_comportament"]
  return df_p

In [ ]:
def processar_clients(df_p):
  clients_fact_risc_df = obtenir_segment_i_factor(df_p)
  clients_fact_edat_df = obtenir_factor_edat(clients_fact_risc_df)
  clients_risc_df = calcular_risc(clients_fact_edat_df)
  return clients_fact_risc_df

In [ ]:
def mostrar_dataframe(df_p):
  display(df_p)

Quins clients s'han de contactar primer en una campanya de retargeting?

Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents? (Per exemple: un client jove que abandona la cistella de compra fa 24 h té el mateix risc que un de més edat?)

Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?

Quin client seria el més rendible de recuperar? Interpretant el risc final i el segment.

In [ ]:
def mostrar_respostes(df_p):
  focus_campanya = df_p.sort_values(by = "risc", ascending = False)["nom"].head(3)
  focus_filtrat = focus_campanya.iloc[1:]
  client_top = focus_campanya = df_p.sort_values(by = "risc", ascending = False)["nom"].head(1)
  clients_no_rentables = df_p.sort_values(by = "codi_comportament", ascending = True)["nom"].head(3)
  df_p.loc[df_p["nom"].isin(focus_filtrat), "missatge"] = "Prioritat alta"
  df_p.loc[df_p["nom"].isin(client_top), "missatge"] = "Prioritat màxima"
  df_p.loc[df_p["nom"].isin(clients_no_rentables), "missatge"] = "Prioritat mínima"
  print(f"Els clients que primer s'hauria de contactar en cas de campanya de retargeting són: \n{df_p.sort_values(by = "risc", ascending = False)["nom"].head(3)}. Índex basat en factor de comportament i factor d'edat.")
  print(f"En aquest factor de risc els valors que més l'augmenten són les edats baixes i factors de comportament alts, és a dir, perfils que deixen la compra a la cistella abandonat més de 24h.")
  print(f"Els clients en els que no val la pena invertir-hi són aquells que naveguen, però no afegeixen productes, o que afegeixen productes, però no arriben al check out. Aquests clients són: \n{df_p.sort_values(by = "codi_comportament", ascending = True)["nom"].head(3)}.")
  print(f"El perfil del client més rendible ha de ser un perfil jove amb un risc alt, és a dir: \n{df_p.sort_values(by = "risc", ascending = False)["nom"].head(1)}")
  return df_p

Por último, se ensambla la función final.

In [ ]:
def main_marketing(df_p):
  df_clients = processar_clients(df_p)
  df_respostes = mostrar_respostes(df_clients)
  mostrar_dataframe(df_respostes)

In [ ]:
main_marketing(clients_df)

Els clients que primer s'hauria de contactar en cas de campanya de retargeting són:
0     Laura Serra
9     Núria Costa
4    Mónica Pérez
Name: nom, dtype: object. Índex basat en factor de comportament i factor d'edat.
En aquest factor de risc els valors que més l'augmenten són les edats baixes i factors de comportament alts, és a dir, perfils que deixen la compra a la cistella abandonat més de 24h.
Els clients en els que no val la pena invertir-hi són aquells que naveguen, però no afegeixen productes, o que afegeixen productes, però no arriben al check out. Aquests clients són:
7      Eva Martín
5     Luis García
8    Diego Romero
Name: nom, dtype: object.
El perfil del client més rendible ha de ser un perfil jove amb un risc alt, és a dir:
0    Laura Serra
Name: nom, dtype: object

,id_client,nom,edat,grup_edat,codi_comportament,factor_comportament,factor_edat,risc,missatge
0,1,Laura Serra,23,18-25,4,0.90,1.20,1.0800,Prioritat màxima
1,2,Marc Vidal,35,26-40,3,0.75,1.00,0.7500,NaN
2,3,Ana López,29,26-40,2,0.50,1.00,0.5000,NaN
3,4,Joan Riera,19,18-25,2,0.50,1.20,0.6000,NaN
4,5,Mónica Pérez,47,41-60,4,0.90,0.85,0.7650,Prioritat alta
5,6,Luis García,52,41-60,1,0.25,0.85,0.2125,Prioritat mínima
6,7,Pilar Sánchez,61,60+,3,0.75,0.70,0.5250,NaN
7,8,Eva Martín,38,26-40,0,0.10,1.00,0.1000,Prioritat mínima
8,9,Diego Romero,24,18-25,1,0.25,1.20,0.3000,Prioritat mínima
9,10,Núria Costa,33,26-40,4,0.90,1.00,0.9000,Prioritat alta

## Nivell 2

### Exercici 1: Gestió de risc i priorització de pacients

Treballes com a analista de dades en un centre mèdic especialitzat. Diversos pacients han enviat els seus símptomes a través d'un formulari online, però les dades arriben en un format desordenat i poc estructurat, i l'equip mèdic necessita que els organitzis per poder prioritzar l'ordre d'atenció segons la gravetat.

In [ ]:
pacients = [
    "Maria|45|tos, Fiebre Alta, dolor_pecho",
    "Luis|33|dolor_cabeza,faTiga",
    "Sara|67|fiebre alta, dificultad RESPIRAR, tos",
    "Jordi|52|fatiga , tos",
    "Anna|29|fiebre alta,dolor_cabeza"
]

nivells_risc = {
    "fiebre_alta": 3,
    "dificultad_respirar": 5,
    "dolor_pecho": 4,
    "tos": 1,
    "fatiga": 1,
    "dolor_cabeza": 1
}

L'objectiu és transformar aquestes dades en informació útil per als metges. A partir dels registres en brut, has de:

- Convertir cada string en una estructura neta (diccionari o similar).
- Separar i normalitzar la llista de símptomes:
  * minúscules
  * eliminar espais
  * dividir correctament per comes
- Assignar un risc a cada símptoma utilitzant el diccionari nivells_risc.
- Calcular el risc total de cada pacient sumant els valors.
- Ordenar els pacients de major a menor risc per determinar la prioritat d'atenció.

**Important**

En aquest Nivell 2 ja no et proporcionem la llista de funcions que has de crear. Ets tu qui ha de plantejar quines funcions necessites i com modularitzar el procés.

Tot i així, es recomana que:

- La funció principal orquestri tots els passos.
- Cada subfunció faci una sola tasca concreta (neteja, conversió, càlcul, ordenació...).
- La lògica estigui separada de manera neta i coherent.

**Resultat esperat**
Un DataFrame o un diccionari amb:

- nom
- edat
- símptomes normalitzats
- risc_total
- I un apartat final amb els pacients ordenats per prioritat (més risc → primer).

La primera función será para la limpieza de la lista de pacientes. Primero de todo se eliminaran los "|", luego se pasa a tipo dataframe para poder usar métodos propios de pandas. Una vez en formato dataframe se pasa todo a minúscula (`.lower()`), y se modifican las "_" por espacios. Por último, mediante un `apply` interactuamos línia por línia de la columna "símptomes". Este método lo usamos para hacer un `strip()`de los diferentes elementos, haciendo `split()` cada vez que haya "," y por último, volviendo a unir mediante `.join.` con un ", ".

In [ ]:
import pandas as pd

Esta primera función servirá para limpiar el texto y preparar un dataframe con los nombres de las/los pacientes, su edad y los síntomas. Esto se hará primero de todo con un split() separando por el carácter (|), que observando los datos en crudo parece el separador de columnas. Hecha esta primera limpieza, se pasa el objeto de lista a dataframe y se da nombre a las diferentes columnas.

Una vez separadas las columnas, se procede a limpiarlas, pasando todos los caracteres a minúscula (lower()), eliminando espacios del inicio y el final de cada string (strip()) y cambiando los `"_"` por espacios (replace("_", " ")). Para poder aplicar correctamente todos estos métodos se usa .str; de esta manera, el método se aplica a cada string de cada fila individualmente, ya que no se puede aplicar a toda la columna a la vez.

Mediante una función lambda, que coge cada celda de una columna y la trata individualmente, se parte cada elemento por la coma y se vuelve a unir con ", ", es decir, se unifican y eliminan los espacios innecesarios alrededor de las comas que pueden conducir a error más adelante.

Por último, se hace un split(",") para crear una lista temporal de elementos que poder luego expandir a una fila por elemento con un .explode(). De esta manera, cada síntoma tiene una fila individual. Esta estructura es necesaria para aplicar la función final.

In [ ]:
def tractament_dades_pacients(llista_p):
  llista_p = [paraules.split("|") for paraules in llista_p]
  df_net = pd.DataFrame(llista_p, columns=["nom", "edat", "símptomes"])
  df_net["símptomes"] = df_net["símptomes"].str.lower().str.strip().str.replace("_", " ")
  df_net["símptomes"] = df_net["símptomes"].apply(
         lambda valor: ",".join([paraula.strip() for paraula in valor.split(", ")]))
  df_net["símptomes"] = df_net["símptomes"].str.split(",")
  df_net = df_net.explode("símptomes").reset_index(drop=True)
  return df_net

Esta segunda función tiene como objetivo limpiar los datos de la tabla original. Únicamente pasa al texto a minúscula, modifica las "_" por espacios y lo guarda todo una vez spliteado como el valor por cada clave del diccionario.

In [ ]:
def nivells_risc_f(dicc_p):
  dicc_net = {
      clau.lower().strip().replace("_", " "): valor
      for clau, valor in dicc_p.items()
  }
  return dicc_net

Por último, se genera una función que unifica la limpieza. Esta simplemente aplica las dos funciones creadas y aplica el método .map. Este método se aplicará sobre una nueva columna llamada "nivell_risc" y lo que hara será aplicar la columna no coincidente del diccionario síntoma:puntuación a la columna de síntomas del df de pacientes/síntomas.

Por último, gracias a una agrupacion (groupby()) según el nombre, se suman los niveles de riesgo de cada paciente y se ordenan (sort_values) según el nivel de riesgo resultante de la suma de manera descendiente (ascending = False).

In [ ]:
def unificacio_neteja(llista_p, dicc_p):
  df_p_net = tractament_dades_pacients(llista_p)
  dicc_p_net = nivells_risc_f(dicc_p)
  df_p_net["nivell_risc"] = df_p_net["símptomes"].map(dicc_p_net)
  return df_p_net.groupby('nom')[['nivell_risc']].sum().sort_values(by="nivell_risc", ascending = False)

In [ ]:
unificacio_neteja(pacients, nivells_risc)

       nivell_risc
nom
Sara             9
Maria            8
Anna             4
Luis             2
Jordi            2

### Exercici 2: Classificació de clients de segurs

In [ ]:
# Tens la següent llista de clients:
clients = [
    {"nom": "Ana", "edat": 42, "codi": 0},
    {"nom": "Carlos", "edat": 30, "codi": 2},
    {"nom": "Isabel", "edat": 55, "codi": 3},
    {"nom": "Jorge", "edat": 40, "codi": 1},
    {"nom": "Marta", "edat": 28, "codi": 0}
]

# I aquest diccionari amb les categories del sistema:
nivells_seguro = {
    0: {"categoria": "Baix risc", "preu_base": 120, "fraude": 0.01},
    1: {"categoria": "Risc mitjà", "preu_base": 200, "fraude": 0.05},
    2: {"categoria": "Risc alt", "preu_base": 350, "fraude": 0.15},
    3: {"categoria": "Risc crític", "preu_base": 500, "fraude": 0.30}
}

El preu final s'ha de calcular amb la fórmula:

```
preu_final = preu_base * (1 + edat/100)
```

Objectius
- Classificar cada client utilitzant nivells_seguro (sense if/elif).
- Afegir:
  * La categoria
  * El preu base
  * La probabilitat de frau
- Calcular el preu final de la pòlissa amb la fórmula donada.
- Crear un DataFrame o diccionari amb la informació final.
- Ordenar els clients:
  * Per probabilitat de frau (descendent).
  * Per preu final.

**Important**

Igual que a l'Exercici 1, en aquest nivell ets tu qui ha de definir les funcions necessàries. Es recomana mantenir el codi modular, on:
- Cada funció resol un pas del procés.
- La funció principal delega totes les tasques.

**Resultat esperat**

Un DataFrame o un diccionari amb:

- Nom
- Edat
- Categoria
- Preu_base
- Preu_final
- Probabilitat_frau

Un apartat d'anàlisi on s'indiqui:
- Quin client té més probabilitat de frau
- Quin té el preu final més alt
- Qui seria prioritari de revisar manualment

In [ ]:
import pandas as pd

Con esta primera función se transforman la lista clients y el diccionario nivells_seguro en dataframes. Este último, aplicándole una reorientación/transposición.

In [ ]:
def preu_client(llista_p, dicc_p):
  clients_df = pd.DataFrame(clients)
  nivells_df = pd.DataFrame.from_dict(nivells_seguro, orient="index")
  resultat = clients_df.merge(nivells_df, left_on="codi", right_index=True, how="left")
  return resultat

Esta segunda función aplica el cálculo.

In [ ]:
def calcul_final(df_p):
  df_p["preu_final"] = df_p["preu_base"] * (1 + df_p["edat"]/100)
  return df_p

La tercera función sirve para ordenar la tabla resultante de las dos maneras que pide el enunciado, según fraude y precio final del seguro.

In [ ]:
def ordre(df_p):
  df_fraud = df_p.sort_values("fraude", ascending = False)
  df_preu = df_p.sort_values("preu_final")
  return df_fraud, df_preu

Por último, la función para unirlas a todas.

In [ ]:
def clients_unificat(llista_p, dicc_p):
  preu_client_df = preu_client(llista_p, dicc_p)
  calcul_final_df = calcul_final(preu_client_df)
  df_fraud, df_preu = ordre(calcul_final_df)
  print("Ordenat per frau (de més a menys):")
  print(df_fraud)
  print("\nOrdenat per preu final (de menys a més):")
  print(df_preu)

In [ ]:
clients_unificat(clients, nivells_seguro)

Ordenat per frau (de més a menys):
      nom  edat  codi    categoria  preu_base  fraude  preu_final
2  Isabel    55     3  Risc crític        500    0.30       775.0
1  Carlos    30     2     Risc alt        350    0.15       455.0
3   Jorge    40     1   Risc mitjà        200    0.05       280.0
0     Ana    42     0    Baix risc        120    0.01       170.4
4   Marta    28     0    Baix risc        120    0.01       153.6

Ordenat per preu final (de menys a més):
      nom  edat  codi    categoria  preu_base  fraude  preu_final
4   Marta    28     0    Baix risc        120    0.01       153.6
0     Ana    42     0    Baix risc        120    0.01       170.4
3   Jorge    40     1   Risc mitjà        200    0.05       280.0
1  Carlos    30     2     Risc alt        350    0.15       455.0
2  Isabel    55     3  Risc crític        500    0.30       775.0

**Respostes exercici:**

- Quin client té més probabilitat de frau: El client amb més probabilitat de frau és Isabel.
- Quin té el preu final més alt: El preu més alt el té també Isabel.
- Qui seria prioritari de revisar manualment: Carlos, ja que essent més jove que Jorge té un perill més alt.

## Nivell 3


### Exercici 1: Generador de contrasenyes segures

**Requisits del generador**


Has de crear una funció principal i totes les subfuncions necessàries per:

- Generar contrasenyes de longitud variable.
-Decidir si han d'incloure:
  * Majúscules
  * Minúscules
  * Números
  * Signes especials
- Assegurar-te que com a mínim apareix un caràcter de cada tipus seleccionat.
- Aleatoritzar completament la contrasenya.
- Retornar la contrasenya generada.

La funció principal del generador ha de tenir valors per defecte, exactament els següents:

- majuscules=True
- minuscules=True
- numeros=True
- signes=False

Aquests paràmetres són obligatoris i formen part del disseny del sistema.

In [ ]:
from numpy import random
import string

La primera función sirve para generar un string con las opciones seleccionadas. De manera predeterminada se encuentran activadas las mayúsculas, minúsculas y números, y desactivados los signos.

Se recorren los parámetros comprobando qué opciones están habilitadas, y se genera con el paquete string una cadena de esa tipología de carácter aleatoria.

Saltará un error en caso de deshabilitar todas las opciones.

In [ ]:
def aleatoritzacio(majuscules=True, minuscules=True, numeros=True, signes=False):
  contrasenya = ""
  if majuscules:
    contrasenya += string.ascii_uppercase
  if minuscules:
    contrasenya += string.ascii_lowercase
  if numeros:
    contrasenya += string.digits
  if signes:
    contrasenya += string.punctuation
  if not contrasenya:
      raise ValueError("Has de seleccionar almenys un tipus de caràcter")
  return contrasenya

La segunda función hace una selección aleatoria de n = longitud indicada en los parámetros y aplica un `join`, ya que el resultado de `random.choice` es un array.

Después se comprueba que en la cadena resultante se cumplan los requisitos de los parámetros, es decir, si mayúsculas está activo, se comprueba que en la cadena haya un valor incluido en `string.ascii_uppercase`, es decir, un carácter tipo letra mayúscula. Así con todos los tipos de caracteres.

Como el parámetro `str_p` ya incluye todos los tipos seleccionados de caracteres, no hace falta activar la primera función de nuevo, sinó que únicamente es necesario hacer shuffles hasta encontrar una combinación que cumpla los requisitos.

Si se cumplen todas las condiciones se devuelve la contraseña.

In [ ]:
def validacio_contrasenya(str_p, longitud_p, majuscules=True, minuscules=True, numeros=True, signes=False):
  while True:
    caracters = random.choice(list(str_p), size=longitud_p, replace=True)
    contrasenya = "".join(caracters)
    requisits = True
    if majuscules and not any(c in string.ascii_uppercase for c in contrasenya):
      requisits = False
    if minuscules and not any(c in string.ascii_lowercase for c in contrasenya):
      requisits = False
    if numeros and not any(c in string.digits for c in contrasenya):
      requisits = False
    if signes and not any(c in string.punctuation for c in contrasenya):
      requisits = False
    if requisits:
      return contrasenya

Última función para unificar las dos anteriores.

In [ ]:
def creacio_contrasenya(longitud_p, majuscules=True, minuscules=True, numeros=True, signes=False):
  cadena_aleatoria = aleatoritzacio(majuscules, minuscules, numeros, signes)
  contrasenya_validada = validacio_contrasenya(cadena_aleatoria, longitud_p, majuscules, minuscules, numeros, signes)
  return contrasenya_validada

Muestra:

In [ ]:
contrasenya = creacio_contrasenya(12, majuscules=True, minuscules=True, numeros=True, signes=False)
print("Contrasenya generada:", contrasenya)

Contrasenya generada: VCsNNqO4tfvO

### Exercici 2: Processament automàtic de dades esportives

**Objectius**

Mitjançant un codi modular, clar i documentat, el teu programa ha de calcular:

- 1.Quin equip és el més golejador.
- 2.Quin és el més golejat.
- 3.El nombre total de gols que ha fet cada equip.
- 4.La classificació final ordenada per punts on cada victòria suma 3 pts, cada empat 1 pts y cada derrota 0 pts.

En aquest nivell no es dona cap funció. Ets tu qui ha de dissenyar un flux complet. El codi ha de reflectir una bona organització interna.

In [44]:
import pandas as pd
from google.colab import drive
ruta = drive.mount('/content/drive/MyDrive/ITAcademy/historicpartits.txt')
with open(ruta) as f:
    lines = f.readlines()

ValueError: Mountpoint must be in a directory that exists